### PR TITLE
Include boundaries in non-exact regex

### LINKED ISSUE #18: ipv4 adress '192.168.0.2000000000' is legal
Was trying out your regular expressions. Did a little testing. It works great, except I'm pretty sure each octet is only 8 bits, and should not exceed a value of 255. That's from memory.

### PR DESCRIPTION
**Pull request by Mottie**
Customized boundaries are added to the regular expression for non-exact matches.

I wasn't sure if we needed to deal with a protocol for non-exact regular expressions; I mention this because I noticed one (negative) test includes a `http://` protocol.

Fixes #18 
Fxies #19

### CODE REVIEW

**Comment by Mottie** [comment]
Hmm, my tests are passing locally. I'm using node v9.9.0 & npm v5.7.1.

**Comment by sindresorhus** [comment]
@Mottie Seems like it now generates an invalid regex on Node.js 4 and 6: https://travis-ci.org/sindresorhus/ip-regex/jobs/358096638 I get this locally too.

**Comment by sindresorhus** [comment]
Ah, you're using lookbehinds. They're only supported on Node.js 10: http://node.green/#ES2018-features--RegExp-Lookbehind-Assertions Weird that it passes on Node.js 8.

**Comment by Mottie** [comment]
What if we add a node version check? If v8 or less, set the `b` variable to `\\b`. This change would cause the tests for `::`, `1::` and `::1` to fail. It's not ideal, unless you want to set the minimum node version to 8+.

The only other option would be to leave the library as-is.

**Comment by sindresorhus** [comment]
I'm ok with just targeting Node.js 8. Just add a note in the readme which version people should use for Node.js 6 support.

**Comment by Mottie** [comment]
I copied the note from https://github.com/sindresorhus/query-string.

**Pull request merged**
