### PR TITLE
Add IPv4 private IP range check option

### PR DESCRIPTION
**Pull request by Mastercuber**
Hi,
this PR introduces a new option called `isPrivate: boolean`. With this option, it is possible to check if a IPv4 address is in the [private address range](https://en.wikipedia.org/wiki/Private_network).

For some applications - like starting a dev server only with a private IP address - it seems to be handy, to be able to check if an IP address is private or public.

Some tests are included. This PR also extracts the IP octet as a constant, for making the regex's more readable.

### CODE REVIEW

**Comment by Mastercuber** [comment]
The tests and type definitions are fine (on node 20..). The linter problem was there before I started working on the PR, and is still there.

**Comment by sindresorhus** [comment]
While I appreciate the pull request, I'm not sure it makes sense to further complicate this package. The main goal is to extract and (naively) validate IPs. For more detailed IP inspection, it's better to use a proper IP parser: https://github.com/indutny/node-ip

**Comment by Mastercuber** [comment]
If that's to much, feel free to close the PR and thanks for the link to the node-ip package

**Comment by silverwind** [comment]
I too think as well that this is out of scope for a validation package. Keep it slim.

**Pull request closed without merging**
